name: shellcheck
on:
  push:
    branches:
    - 'master'
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        severity: error
